apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: cert-manager
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: cert-manager
        namespace: cert-manager
      spec:
        interval: 10m0s
        url: https://charts.jetstack.io

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: cert-manager
        namespace: cert-manager
      spec:
        interval: 1h
        releaseName: cert-manager
        chart:
          spec:
            chart: cert-manager
            # renovate: datasource=helm depName=cert-manager registryUrl=https://charts.jetstack.io
            version: v1.19.2
            sourceRef:
              kind: HelmRepository
              name: cert-manager
        values:
          crds:
            enabled: true
            keep: true
          config:
            apiVersion: controller.config.cert-manager.io/v1alpha1
            kind: ControllerConfiguration
            enableGatewayAPI: true
          extraArgs:
            - --enable-gateway-api