apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: descheduler
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: descheduler
        namespace: kube-system
      spec:
        interval: 10m0s
        url: https://kubernetes-sigs.github.io/descheduler/

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: descheduler
        namespace: kube-system
      spec:
        interval: 1h
        releaseName: descheduler
        chart:
          spec:
            chart: descheduler
            # renovate: datasource=helm depName=descheduler registryUrl=https://kubernetes-sigs.github.io/descheduler/
            version: 0.35.0
            sourceRef:
              kind: HelmRepository
              name: descheduler
        values:
