apiVersion: v1
kind: Secret
metadata:
    name: immich-client
    namespace: dex
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:Y7w9Pp1L,iv:tJFzMtk8dHrIfpSvl4Jh1FetbEy+zJwBRBMogHDQE+o=,tag:GYJ9w/1gV4eGDElwHCz1BQ==,type:str]
    client-secret: ENC[AES256_GCM,data:cM9J56/XeQ3Ejw/fyWff844Hm2SYSTUpRgFrkYv6A9k=,iv:B222qkc8fgqlBCPcqa9PeZI54At6/J49JvuUkBAkMKs=,tag:gEb2OgIr8jBoNdgY3CRwZA==,type:str]
sops:
    age:
        - recipient: age1x4tnetzytdsxqgj3glxz0g6ml7qgannsp60dqvdt5ztvm9csnyxqqu52tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbjFsVVVCN1dmZmo0Zk9P
            WDloS3ZPRWlqcnZLMHk1MDhWaTlDQTFUU1dZCmppZDBJRzFWTnU1T1hLMjNaNWNx
            WmwybWxVRXNqZk5vNnNXbG9sL0ZTV00KLS0tIHovNWF2T3JXUUlCRDdXYmJYck5U
            QTVpZkZDOEJUMXlJR1NZbEZHNmhwaDQKoiXGUbrkPLv1xmGvq78q9fXKgrHx/I8r
            yfU3F63Rm7wU6EaoI7vVdYi2Dheo8IvBQ4ilRMjrDFqTSGpfJzuGhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T05:19:15Z"
    mac: ENC[AES256_GCM,data:Kz6+ffoLbebDQmgkcDiBVJ+jiCV8EVE4DOxkArn/MQpz1nN+gR+pR1dom4GdtGILUF5ioJq8Jg44ySMeh35JFMKj8WV0T3V7Xk/2pfBBHnuz4ZS5bGw4x7rwbq8It8ZsfRqT/KwS7DUdsU2afUysZdocvvdHet90nBeN/WCN6P8=,iv:Gs174Cohq7CRCcnO+W35sV6LbBK4s0tA+IRB7Dgr27c=,tag:jbhA0y3qxWTXRU4w6k3ZxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
