apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-oauth-credentials
  namespace: dex
stringData:
  client-id: ENC[AES256_GCM,data:75VLuSptHhYVHfQRlZo4e6yRAug=,iv:c7UTk6fMJnKqLU7yV7HW37VqO/CamgGKaHjFJEi4YM4=,tag:TxLNSDNhTs1jppOGuheilg==,type:str]
  client-secret: ENC[AES256_GCM,data:RS5tXDsH6r8f5794JLOrrMTNEJOPf5ZXe3UfMeelSQ/JjnPuAyiM7Q==,iv:QYZIl6EN9VzvIkv8b+Bgeq7uzY8Iha5Zb8xPgIkX4co=,tag:G1q1TVC5SqD7NOoxJxDJXA==,type:str]
sops:
  age:
    - recipient: age1x4tnetzytdsxqgj3glxz0g6ml7qgannsp60dqvdt5ztvm9csnyxqqu52tc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudXV4OHFJc0hSNkpTNG1t
        RmdGZHpuTzEwRDNXY0RNS3ZxcHoyUEFhWnpBCnVUQ0xyMUJwNk5BRng1aURJTTJP
        bXZid3o2bklMaFR6RVdNY3Vycjg1RDQKLS0tIHJoclNyc3k5TWFrRGdZQ1dqTmFh
        YklxeVcwQjZHOHQrSFFHbWVoWU5ORVEKM42ifNFy1FBDQURyQzDa/Xyi6QSYGWCL
        yDQiHxyloqaXCuAQifNO1SUTuRxonVGF4LuGksyHHUmWVv8+oKx0HA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-21T11:02:54Z"
  mac: ENC[AES256_GCM,data:wtGj/Zn83CTNpdTyYU4mOzInXMRvDmWM66jj0LULLD55Hz+aLtFvim+UOsqt7g9FfBNbeFPVH28NscGIFM7ok6l2IkLVBhzBELm+A4i0QnCwFzFw3WuAjLhVYg8xTGA4eVQdgHNVPrAYRQW7nKnkFzFj08G2JV5mT3vg1tv3LdI=,iv:R6/7Nz6qNyxWph6dAK+3jRLz11Nfm3CKPf6hje+/qyQ=,tag:9uneVP/upFQ/86QboNJyHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
