---
apiVersion: v1
kind: Namespace
metadata:
  name: dex

---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: dex
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: dex
        namespace: dex
      spec:
        interval: 10m0s
        url: https://charts.dexidp.io

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: dex
        namespace: dex
      spec:
        interval: 1h
        releaseName: dex
        chart:
          spec:
            chart: dex
            # renovate: datasource=helm depName=dex registryUrl=https://charts.dexidp.io
            version: 0.24.0
            sourceRef:
              kind: HelmRepository
              name: dex
        values:
          config:
            # Set it to a valid URL
            issuer: https://dex.homelab.evilcyborgdrone.com

            # See https://dexidp.io/docs/storage/ for more options
            storage:
              type: memory

            # Enable at least one connector
            # See https://dexidp.io/docs/connectors/ for more options
            connectors:
              - type: github
                # Required field for connector id.
                id: github
                # Required field for connector name.
                name: GitHub
                config:
                  # Credentials can be string literals or pulled from the environment.
                  clientID: $GITHUB_CLIENT_ID
                  clientSecret: $GITHUB_CLIENT_SECRET
                  redirectURI: https://dex.homelab.evilcyborgdrone.com/callback
                  orgs:
                    - name: farrell-white
                  teamNameField: slug
                  useLoginAsID: false

            staticClients:
              - id: "kube-apiserver"
                public: true
                redirectURIs:
                  - http://localhost:8000
                  - http://localhost:18000
                name: kube-apiserver

          envVars:
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-oauth-credentials
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-oauth-credentials
                  key: client-secret

          ingress:
            enabled: true
            hosts:
              - host: dex.homelab.evilcyborgdrone.com
                paths:
                  - path: /
                    pathType: Prefix
            annotations:
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            tls:
              - hosts:
                  - dex.homelab.evilcyborgdrone.com
                secretName: dex-tls

    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: oidc-cluster-admin
      subjects:
      - kind: User
        name: mark.andrew.farrell@gmail.com
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: cluster-admin
        apiGroup: rbac.authorization.k8s.io
