---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: envoy-gateway
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: envoy-gateway

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: envoy-gateway
        namespace: envoy-gateway
      spec:
        interval: 10m
        url: oci://docker.io/envoyproxy/gateway-helm
        ref:
          # renovate: datasource=docker depName=docker.io/envoyproxy/gateway-helm
          semver: 1.6.3

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: envoy-gateway
        namespace: envoy-gateway
      spec:
        interval: 1h
        releaseName: envoy-gateway
        chartRef:
          kind: OCIRepository
          name: envoy-gateway
        values: {}

---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: envoy-gateway-config
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: gateway.envoyproxy.io/v1alpha1
      kind: EnvoyProxy
      metadata:
        name: proxy
        namespace: envoy-gateway
      spec:
        provider:
          type: Kubernetes
          kubernetes:
            envoyService:
              annotations:
                metallb.io/loadBalancerIPs: 10.0.2.4

    - apiVersion: gateway.networking.k8s.io/v1
      kind: GatewayClass
      metadata:
        name: envoy-gateway
      spec:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller

    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: envoy-gateway
        namespace: envoy-gateway
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod-gateway-api
      spec:
        gatewayClassName: envoy-gateway
        infrastructure:
          parametersRef:
            group: gateway.envoyproxy.io
            kind: EnvoyProxy
            name: proxy

        listeners:
          # ACME SOLVER LISTENER
          - name: http
            protocol: HTTP
            port: 80
            allowedRoutes:
              namespaces:
                from: All

          # DEX LISTENER
          - name: dex-homelab-evilcyborgdrone-com-https
            hostname: "dex.homelab.evilcyborgdrone.com"
            port: 443
            protocol: HTTPS
            allowedRoutes:
              namespaces:
                from: All
            tls:
              mode: Terminate
              certificateRefs:
                - name: dex-homelab-evilcyborgdrone-com-tls

          # FLUX LISTENER
          - name: flux-homelab-evilcyborgdrone-com-https
            hostname: "flux.homelab.evilcyborgdrone.com"
            port: 443
            protocol: HTTPS
            allowedRoutes:
              namespaces:
                from: All
            tls:
              mode: Terminate
              certificateRefs:
                - name: flux-homelab-evilcyborgdrone-com-tls

          # GRAFANA LISTENER
          - name: grafana-homelab-evilcyborgdrone-com-https
            hostname: "grafana.homelab.evilcyborgdrone.com"
            port: 443
            protocol: HTTPS
            allowedRoutes:
              namespaces:
                from: All
            tls:
              mode: Terminate
              certificateRefs:
                - name: grafana-homelab-evilcyborgdrone-com-tls
