apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: flux-operator
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: flux-operator
        namespace: flux-system
      spec:
        interval: 10m
        url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
        ref:
          # renovate: datasource=docker depName=ghcr.io/controlplaneio-fluxcd/charts/flux-operator
          semver: 0.39.0

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: flux-operator
        namespace: flux-system
      spec:
        interval: 1h
        releaseName: flux-operator
        chartRef:
          kind: OCIRepository
          name: flux-operator
        values:
          web:
            config:
              baseURL: "https://flux.homelab.evilcyborgdrone.com"
              authentication:
                type: OAuth2
                oauth2:
                  provider: OIDC
                  issuerURL: "https://dex.homelab.evilcyborgdrone.com"
            ingress:
              enabled: true
              className: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
              hosts:
                - host: flux.homelab.evilcyborgdrone.com
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - secretName: flux-operator-tls
                  hosts:
                    - flux.homelab.evilcyborgdrone.com
        valuesFrom:
          - kind: Secret
            name: flux-web-client
            valuesKey: client-id
            targetPath: web.config.authentication.oauth2.clientID
          - kind: Secret
            name: flux-web-client
            valuesKey: client-secret
            targetPath: web.config.authentication.oauth2.clientSecret

    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: flux-operator
        namespace: flux-system
      spec:
        parentRefs:
          - name: envoy-gateway
            namespace: envoy-gateway
            kind: Gateway
        hostnames:
          - "flux.homelab.evilcyborgdrone.com"
        rules:
          - backendRefs:
              - group: ""
                kind: Service
                name: flux-operator
                port: 9080
                weight: 1
            matches:
              - path:
                  type: PathPrefix
                  value: /
