apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: grafana-operator
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: grafana-operator
        namespace: grafana
      spec:
        interval: 10m0s
        url: https://grafana.github.io/helm-charts

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: grafana-operator
        namespace: grafana
      spec:
        interval: 1h
        releaseName: grafana-operator
        chart:
          spec:
            chart: grafana-operator
            # renovate: datasource=helm depName=grafana-operator registryUrl=https://grafana.github.io/helm-charts
            version: 5.21.2
            sourceRef:
              kind: HelmRepository
              name: grafana-operator
        values:
