apiVersion: v1
kind: Secret
metadata:
    name: restic-repo-password
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Ubk/v2KUfCalKPu4g7uGmetgaQKacJfkyH5bKbmQsojIf+A5sJ6KNMRrrJY=,iv:NRTmRXCTups2Qr1dlcwq+gg2vt+5m9jbpfx1IDUzSrw=,tag:PhZ814fa2LqNOm6wKOT0Mw==,type:str]
sops:
    age:
        - recipient: age1x4tnetzytdsxqgj3glxz0g6ml7qgannsp60dqvdt5ztvm9csnyxqqu52tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcTZtMVpWamRiRGF0RE9Y
            OXliYnd2Q2RyUEQrclQvY1BtM0ttOENCOWc0CnJFa1RRaVQyanUrOWJzSk1vUm9G
            cFZqT3JQbSs5N0UzZ2R6OUprSi9BeHcKLS0tIG5aYk4zU2V1bDVmMkI4KzFxR3I1
            OE5YZWwzNFptSjdGOW8vaDBnMXpyOEkKslu1Oqyffl8U8MSlnUc93ASV0mH7ImU/
            ai7+yCjcGq4WSy89o7ASjfrj0rKtmWCmJkze8aq4hoCY2wWdoQrzow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T09:59:48Z"
    mac: ENC[AES256_GCM,data:8NPYXwXgnq0g6cq3/pytqIGhWVZlojd43gCPFTvXPP9uAMdiHCkccftrooncETvJ3RnL+1q/4rhoVYDf4FiZ9vdU7gQOUUJrlfCimdcpFfh/ypZH756SGa52sDLIP89AZXu+hfWuNPlLKwOdS3U3udZN3jNKZy0RirB0cvUfA0g=,iv:QbUUE96otle9OGBqWfoOfRf+le6+Rt+lww4Q+JFAfns=,tag:HdnCCqxkQpA4lPvNatVXig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
