apiVersion: v1
kind: Secret
metadata:
    name: immich-r2-client
    namespace: immich
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:3tgKkRTw6R+X1/fPtCr0cjF1G31DKNl46Z+1sBynIYc=,iv:CjWXJ31wNUXe7qAQGG45UYr9X9/Kl6LUiH1gLBf2muI=,tag:RjhZDyK6hIDNzfGNLovdVw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:uOxAu/usDJ2FP/KqqOEPXoj3VVEwkvyFNPNWpWduSvGbzcagKCrE8FIvw20yhBa8zQFWGa1KIwe5Iprzf3lCJA==,iv:d7wiDa0IXOY72ZEi9fhJxVlcKlU3Xh06TMxkLmASzM8=,tag:XDcQdOE6lmLfCNc6Vg/T7Q==,type:str]
sops:
    age:
        - recipient: age1x4tnetzytdsxqgj3glxz0g6ml7qgannsp60dqvdt5ztvm9csnyxqqu52tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNVdvZ2sybjJQWjFkV1pS
            SWVuWlppZkd4MjRqM09tYmc0akl1N0oxNmdJCmRMN3BaUEErZlVPeGViQndMRUZs
            NTdoeVd2ZzZtRmtKLytTc1A5aFdiTGsKLS0tIDdRbmZZTE5jUTZyTStqT1NjajFh
            NFlFQjlQRGFYczRKWENibFRtKzlHNFUKHxIugXRtMTAkB0fDxac5fsavqti7KtiS
            seoRx/dZ6rV13l2+zF/mUxRsCuPxXqFMwDDrLJ52KLs4esOWCoVHFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T09:49:02Z"
    mac: ENC[AES256_GCM,data:5N4frnvPydFGSGA2KXTNT3YHpre5N0bQFX1dErjsAjog1Jufu3NyQj0DVnYx0lT86a57D1WdnxXbN4ZT4fBhrN9HpILZ5QL+VMvahiZx9zU586dThpCjyhu3fGLG9LBn6p5ZvIHtRZ9nsxnMcXwAZmhOKJeQnaPxdpHHaFaHTt0=,iv:4ZAoaltC3faO9VT5A3XaZBMeJOmAZzwn4R3DbFKinv0=,tag:MpehV3EFzjj+23FhJ7sCWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
