apiVersion: v1
kind: Secret
metadata:
    name: immich-oidc-credentials
    namespace: immich
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:vhp12v0kJCy1m6hsIEsyUp+we6jnwlVwKv2mWhhR2EHGwDyCGpNIGc7ilhjsOktPXqRrDdmlfOsTdACz1/recm72dbsgEHt3TOakg/ai1gSuM+Ptijdb861cOPLzb7Yb5CT9Fz9a2ZY+0j4ysnPyvw==,iv:ZH76CfvKQ2zMjx1qwIz12hs24uU16M6qh4Bq94/ucG0=,tag:r96BpylMqhFoCAWxe286Jg==,type:str]
sops:
    age:
        - recipient: age1x4tnetzytdsxqgj3glxz0g6ml7qgannsp60dqvdt5ztvm9csnyxqqu52tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaXlLVnczUkVEYnlydExW
            YkpjM0Z1YmtwaENnalRyN3ZNVUlvbDBFM3p3ClNLNEE2QUF4MjNFWHpqcWhtUnAr
            ZjlqMmluVEFWbjR4clV5dUJLNDlsWE0KLS0tIC8wQ3BOZGN2QkZ2Myt1WUc2amZY
            RkRvbjdJckNFYU1ZbmJhek9HWFUxbjgKXLvRYl3dYf4VQRBX3p/tPslOvTI8gOJ8
            7jbA0INpkxwOySN3lZrx6N6pn/wUl2JoKaX3bw+ewZiq/AcVkLGnVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T05:26:11Z"
    mac: ENC[AES256_GCM,data:db98PDV0l85MvTvkPlTIQagmTeLVeMFc813W9D8rxDxUN8mK3Y/s+MELmemdxADjJHokbHO5okjULVwcrksqPDRbZE628lCe8ai004oj2uaaJkEHciF9jN91NTOCUy+daOpTHNTKIoCz4HcYD6wGwL0nAtnbfX8DW3/MX78J63M=,iv:m6Pyzw1joTzxgzGDpIcNGDdyk6UvV3ojI/vrN/gzJ0w=,tag:rD9kyYBonxIwsqouMJbwhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
