---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: kube-state-metrics
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: kube-state-metrics

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: kube-state-metrics
        namespace: kube-state-metrics
      spec:
        interval: 10m
        url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
        ref:
          # renovate: datasource=docker depName=ghcr.io/prometheus-community/charts/kube-state-metrics
          semver: 7.1.0

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: kube-state-metrics
        namespace: kube-state-metrics
      spec:
        interval: 1h
        releaseName: kube-state-metrics
        chartRef:
          kind: OCIRepository
          name: kube-state-metrics
        values:
          annotations:
            reloader.stakater.com/auto: "true"
          collectors: [ ]
          extraArgs:
            - --custom-resource-state-only=true
          rbac:
            extraRules:
              - apiGroups:
                  - source.toolkit.fluxcd.io
                  - kustomize.toolkit.fluxcd.io
                  - helm.toolkit.fluxcd.io
                  - notification.toolkit.fluxcd.io
                  - image.toolkit.fluxcd.io
                  - fluxcd.controlplane.io
                resources:
                  - gitrepositories
                  - buckets
                  - helmrepositories
                  - helmcharts
                  - ocirepositories
                  - kustomizations
                  - helmreleases
                  - alerts
                  - providers
                  - receivers
                  - imagerepositories
                  - imagepolicies
                  - imageupdateautomations
                  - resourcesets
                verbs: [ "list", "watch" ]
              - apiGroups:
                  - tuppr.home-operations.com
                resources:
                  - kubernetesupgrades
                  - talosupgrades
                verbs: [ "list", "watch" ]
          customResourceState:
            enabled: true
            config:
              spec:
                resources:
                  - groupVersionKind:
                      group: kustomize.toolkit.fluxcd.io
                      version: v1
                      kind: Kustomization
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux Kustomization resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          suspended: [ spec, suspend ]
                          revision: [ status, lastAppliedRevision ]
                          source_name: [ spec, sourceRef, name ]
                  - groupVersionKind:
                      group: helm.toolkit.fluxcd.io
                      version: v2
                      kind: HelmRelease
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux HelmRelease resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          suspended: [ spec, suspend ]
                          revision: [ status, history, "0", chartVersion ]
                          chart_name: [ status, history, "0", chartName ]
                          chart_app_version: [ status, history, "0", appVersion ]
                          chart_ref_name: [ spec, chartRef, name ]
                          chart_source_name: [ spec, chart, spec, sourceRef, name ]
                  - groupVersionKind:
                      group: source.toolkit.fluxcd.io
                      version: v1
                      kind: GitRepository
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux GitRepository resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          suspended: [ spec, suspend ]
                          revision: [ status, artifact, revision ]
                          url: [ spec, url ]
                  - groupVersionKind:
                      group: source.toolkit.fluxcd.io
                      version: v1
                      kind: Bucket
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux Bucket resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          suspended: [ spec, suspend ]
                          revision: [ status, artifact, revision ]
                          endpoint: [ spec, endpoint ]
                          bucket_name: [ spec, bucketName ]
                  - groupVersionKind:
                      group: source.toolkit.fluxcd.io
                      version: v1
                      kind: HelmRepository
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux HelmRepository resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          suspended: [ spec, suspend ]
                          revision: [ status, artifact, revision ]
                          url: [ spec, url ]
                  - groupVersionKind:
                      group: source.toolkit.fluxcd.io
                      version: v1
                      kind: HelmChart
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux HelmChart resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          suspended: [ spec, suspend ]
                          revision: [ status, artifact, revision ]
                          chart_name: [ spec, chart ]
                          chart_version: [ spec, version ]
                  - groupVersionKind:
                      group: source.toolkit.fluxcd.io
                      version: v1
                      kind: OCIRepository
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux OCIRepository resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          suspended: [ spec, suspend ]
                          revision: [ status, artifact, revision ]
                          url: [ spec, url ]
                  - groupVersionKind:
                      group: notification.toolkit.fluxcd.io
                      version: v1beta3
                      kind: Alert
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux Alert resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          suspended: [ spec, suspend ]
                  - groupVersionKind:
                      group: notification.toolkit.fluxcd.io
                      version: v1beta3
                      kind: Provider
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux Provider resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          suspended: [ spec, suspend ]
                  - groupVersionKind:
                      group: notification.toolkit.fluxcd.io
                      version: v1
                      kind: Receiver
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux Receiver resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          suspended: [ spec, suspend ]
                          webhook_path: [ status, webhookPath ]
                  - groupVersionKind:
                      group: image.toolkit.fluxcd.io
                      version: v1
                      kind: ImageRepository
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux ImageRepository resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          suspended: [ spec, suspend ]
                          image: [ spec, image ]
                  - groupVersionKind:
                      group: image.toolkit.fluxcd.io
                      version: v1
                      kind: ImagePolicy
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux ImagePolicy resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          suspended: [ spec, suspend ]
                          source_name: [ spec, imageRepositoryRef, name ]
                  - groupVersionKind:
                      group: image.toolkit.fluxcd.io
                      version: v1
                      kind: ImageUpdateAutomation
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux ImageUpdateAutomation resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          suspended: [ spec, suspend ]
                          source_name: [ spec, sourceRef, name ]

                  # flux-operator resources
                  - groupVersionKind:
                      group: fluxcd.controlplane.io
                      version: v1
                      kind: ResourceSet
                    metricNamePrefix: gotk
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Flux ResourceSet resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          ready: [ status, conditions, "[type=Ready]", status ]
                          reconcile: [ metadata, annotations, "fluxcd.controlplane.io/reconcile" ]

                  # tuppr resources
                  - groupVersionKind:
                      group: tuppr.home-operations.com
                      version: v1alpha1
                      kind: KubernetesUpgrade
                    metricNamePrefix: tuppr
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Tuppr KubernetesUpgrade resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          phase: [ status, phase ]
                          currentVersion: [ status, currentVersion ]
                          targetVersion: [ status, targetVersion ]
                          message: [ status, message ]
                  - groupVersionKind:
                      group: tuppr.home-operations.com
                      version: v1alpha1
                      kind: TalosUpgrade
                    metricNamePrefix: tuppr
                    metrics:
                      - name: "resource_info"
                        help: "The current state of a Tuppr TalosUpgrade resource."
                        each:
                          type: Info
                          info:
                            labelsFromPath:
                              name: [ metadata, name ]
                        labelsFromPath:
                          exported_namespace: [ metadata, namespace ]
                          phase: [ status, phase ]
                          version: [ spec, talos, version ]
                          message: [ status, message ]

    - apiVersion: operator.victoriametrics.com/v1beta1
      kind: VMServiceScrape
      metadata:
        name: kube-state-metrics
        namespace: kube-state-metrics
        labels:
          team: kube-state-metrics
      spec:
        namespaceSelector:
          matchNames:
            - kube-state-metrics
        selector:
          matchLabels:
            app.kubernetes.io/name: kube-state-metrics
            app.kubernetes.io/instance: kube-state-metrics
        endpoints:
          - port: http
            path: /metrics
            interval: 10s
            honorLabels: false
