apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: pihole
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: pihole

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: pihole
        namespace: pihole
      spec:
        interval: 10m0s
        url: https://mojo2600.github.io/pihole-kubernetes/

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: pihole
        namespace: pihole
      spec:
        interval: 1h
        releaseName: pihole
        chart:
          spec:
            chart: pihole
            version: v2.*.*
            sourceRef:
              kind: HelmRepository
              name: pihole
        values:
          serviceWeb:
            type: LoadBalancer
            externalTrafficPolicy: Local
            annotations:
              metallb.universe.tf/loadBalancerIPs: 10.0.2.254

          serviceDns:
            mixedService: true
            type: LoadBalancer
            externalTrafficPolicy: Local
            annotations:
              metallb.universe.tf/loadBalancerIPs: 10.0.2.254

          extraEnvVars:
            TZ: Australia/Hobart
            FTLCONF_dns_domain: lan
            FTLCONF_dns_hosts: 10.0.0.1 gateway.lan;10.0.2.1 k.lan;10.0.2.254 pihole.lan;10.0.1.1 k0.lan;10.0.1.2 k1.lan;10.0.1.3 k2.lan;10.0.2.3 vm.lan
            FTLCONF_dns_listeningMode: ALL

          persistentVolumeClaim:
            enabled: true
            storageClass: rook-ceph-block
