apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: reloader
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: reloader

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: reloader
        namespace: reloader
      spec:
        interval: 10m0s
        url: https://stakater.github.io/stakater-charts

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: reloader
        namespace: reloader
      spec:
        interval: 1h
        releaseName: reloader
        chart:
          spec:
            chart: reloader
            # renovate: datasource=helm depName=reloader registryUrl=https://stakater.github.io/stakater-charts
            version: 2.2.7
            sourceRef:
              kind: HelmRepository
              name: reloader
        values:
          reloader:
            reloadStrategy: annotations
