apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: rook-ceph-operator
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: rook-ceph
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: rook-ceph
        namespace: rook-ceph
      spec:
        interval: 10m0s
        url: https://charts.rook.io/release

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: rook-ceph
        namespace: rook-ceph
      spec:
        interval: 1h
        releaseName: rook-ceph
        chart:
          spec:
            chart: rook-ceph
            # renovate: datasource=helm depName=rook-ceph registryUrl=https://charts.rook.io/release
            version: v1.19.0
            sourceRef:
              kind: HelmRepository
              name: rook-ceph
