apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:ozKnLiK+ChbdnSuQOWl6ctc=,iv:GFhfLAtqZThFxMc5AuISgJoCbZNngB6A5L4+74qbgDM=,tag:AS1lqjNmKEIQ8aLxWFe/OA==,type:str]
    client_secret: ENC[AES256_GCM,data:ZGM+uvHZzmeKfkblUy765kJSvQ+rl0bP7O1k7EfkUfymXbLlezg6lK7ltxMIFuhqybn6Z8D3c//9y74/+Jpy,iv:Nwny+iY5+nfgTfDHVnweOgf6EZsO56xLikbI/NLwEB8=,tag:dOxCdzvbJEpD7jpahpKm6g==,type:str]
sops:
    age:
        - recipient: age1x4tnetzytdsxqgj3glxz0g6ml7qgannsp60dqvdt5ztvm9csnyxqqu52tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRVo5cm81OENhRFZUVHRL
            S2RIWisycml1endZdnI0bEwzS2phTDk3S2k0CjlYZHpRV3VQSDRhRFI3cDhON3JG
            ZDdaNXZjTWxkN3BuYTJ5VEQzSjJ5dkUKLS0tIEtXc0VlV1ZUR3J1TFlSdmJvUWhv
            RzNUR2YrTEV3d0J5TlZiZUVxS3pJNXMKySRyPnTaeeqFIDaZcC1GLCQkLv9JieOW
            Wj6IwC5wfgFxcs1oC55Y2tRjMkNmeorGgR4JnX0RULzLvJsi3K6yPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T23:17:35Z"
    mac: ENC[AES256_GCM,data:+vN/CszJXKTJ7EAXxrlXdSD8YFQCK9kwm8iVdmDwZmeTqzNlCqFx9LT8yfq4KPDHEDB2uLGoyC2FhYmWQGSSmo1D2kJLzxHn2mZNRIdig5vgO2Fj64Z5/l/sESpw3h465DUl4srQHhNRxhLl21lM2tNVe+qUPTrJozFMyMPOFcY=,iv:45z+IsIISvN6pUv2rafPaQ3uManNWM92RaoAloknmpM=,tag:Tx004/awS6gwXXltfKeT2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
